language: ruby
rvm:
  - 2.1.10
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.4.3
  - 2.5.0
addons:
  postgresql: 9.3
gemfile:
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_5.gemfile
before_script:
  - createuser -d acts-as-taggable-array-on -U postgres
  - createdb --username=acts-as-taggable-array-on acts-as-taggable-array-on_test
script:
  - bundle
  - bundle exec rspec
matrix:
  exclude:
    - rvm: 2.1.10
      gemfile: gemfiles/rails_5.gemfile
